### ISSUE TITLE
Requesting help from cfmask application exits with FAILURE

### ISSUE THREAD

**Issue by NGenetzky** [USGS-EROS/espa-cloud-masking#29]
When requesting help from the cfmask application the application exits with FAILURE not SUCCESS.
See misc.c function get_args for --help.

**Comment by gschmidt-usgs** [comment]
I would say it should return SUCCESS.

--------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the USGS Earth Resources Observation and Science (EROS) Center
Rapid City, SD  57701
605-593-2722   Phone
605-394-6078   Fax
gschmidt@usgs.gov

Adaptation - "Manage the unavoidable"
Mitigation - "Avoid the unmanageable"

**Comment by rdilley-usgs** [comment]
Effects both L4-7 and L8 versions of the code.

Updated the code to not exit with FAILURE.

**Comment by rdilley-usgs** [comment]
Complete
